# The only good theme among the options.
theme: jekyll-theme-hacker

# Custom blog title.
title: NightShade's Blog

# Custom blog description.
description: My personal blog where I write about stuff.

# Don't want README to be included in the blog.
exclude: [README.md]

# Switch timezone to IST.
timezone: Asia/Kolkata
